### ISSUE TITLE
Sending MIDI to console and not to an output ?

### ISSUE THREAD

**Issue by natcl** [nfroidure/MIDIPlayer#3]
I'd like to integrate MIDIPlayer with Node-RED and would like to access the output stream as bytes without going to an actual MIDI port.  Is this possible ?

**Comment by nfroidure** [comment]
What's the point of writing MIDI events to the console?

**Comment by natcl** [comment]
Actually to be more specific, I want to run this on a Raspberry pi and send the midi stream via the Serial port.

**Comment by nfroidure** [comment]
Creating a stdout MIDI output sharing the same API than the Web MIDI API output will probably do the job.
