### ISSUE TITLE
Play it on chrome 71.0.3578.98

### ISSUE THREAD

**Issue by camiloperezv** [nfroidure/midiplayer#8]
I'm creating a react app which loads an reproduces a midi file. my code is 
```javascript
navigator.requestMIDIAccess().then((midiAccess) => {
  console.log(midiAccess.outputs)
  midiPlayer = new MIDIPlayer({
    	  'output': midiAccess.outputs()[0]
  });
  axios.get('/midi/piano_sonata.mid', {
    responseType: 'arraybuffer'
  }).then((data) => {
    var midiFile = new MIDIFile(data.data);
    console.log(midiFile)
    midiPlayer.load(midiFile);
    midiPlayer.play(function() {
      console.log('Play ended');
    });
  })
})
```
When the code reaches midiPlayer.play throws an error `midiAccess.outputs is not a function`

If I want to check what are the midiAccess I run this code on browser console
`var mid; navigator.requestMIDIAccess().then(function(midiAccess) {mid =midiAccess})`

the mid object has the output prop but it looks like `outputs: MIDIOutputMap {size: 0}`

**Comment by nfroidure** [comment]
You just have no midi output I guess, check http://karaoke.insertafter.com/ to see how it handle that case
